#pragma once

// Hand-written, shared filter-expression parser + evaluator (TCL_EXPLORATION.md
// Phase 2). Not generated by cmg - it's the same code for every class,
// depending only on the per-class metadata Phase 1 generates
// (get_field()/match_hop() - see generated/struct_hpp_j2.py's own comments
// for their exact contract). Grammar (matches UPDATES.md item 15's own
// examples, e.g. `.terminal.name =~ IN* && .layer_name == M4`):
//
//   expr       := or_expr
//   or_expr    := and_expr ('||' and_expr)*
//   and_expr   := unary ('&&' unary)*
//   unary      := '(' expr ')' | comparison
//   comparison := path op literal
//   path       := '.' IDENT ('.' IDENT)*
//   op         := '==' | '!=' | '<=' | '>=' | '<' | '>' | '=~'
//   literal    := '"' ... '"' | "'" ... "'" | BAREWORD
//
// A literal's type isn't decided at parse time - it's kept as raw text
// and compared against whatever PropertyValue::Type the matched field
// actually has at evaluation time (STRING/INT/DOUBLE), so `.width == 100`
// works without the parser having to guess that `width` is numeric.
// Explicit hops only (`.shapes.layer_name`, never an implicit/magic
// `.layer_name`) - see TCL_EXPLORATION.md's "cmg codegen design" section
// for why: one general N-hop resolver, no per-class special-casing.

#include "generated/property.hpp"

#include <cctype>
#include <charconv>
#include <expected>
#include <string>
#include <string_view>
#include <vector>

namespace le
{
    enum class FilterOp
    {
        Eq,
        Ne,
        Lt,
        Le,
        Gt,
        Ge,
        Glob,
    };

    /// @brief A parsed filter expression - either a leaf comparison
    /// (`path op literal`) or a boolean combination of child expressions.
    /// Self-referential via `children` (a std::vector<FilterExpr> member
    /// inside FilterExpr itself), which C++17-and-later's relaxed
    /// incomplete-type support for std::vector allows without extra
    /// indirection.
    struct FilterExpr
    {
        enum class Kind
        {
            Comparison,
            And,
            Or,
        } kind = Kind::Comparison;

        // Valid when kind == Comparison.
        std::vector<std::string> path;
        FilterOp op = FilterOp::Eq;
        std::string literal;

        // Valid when kind == And/Or.
        std::vector<FilterExpr> children;
    };

    namespace filter_detail
    {
        struct Token
        {
            enum class Kind
            {
                Dot,
                Ident,
                Op,
                And,
                Or,
                LParen,
                RParen,
                Literal,
                End,
            } kind;
            std::string text;
        };

        class Lexer
        {
        public:
            explicit Lexer(std::string_view text) : text_(text) {}

            std::expected<Token, std::string> next()
            {
                skip_whitespace();
                if (pos_ >= text_.size())
                    return Token{Token::Kind::End, ""};

                char c = text_[pos_];
                if (c == '.')
                {
                    ++pos_;
                    return Token{Token::Kind::Dot, "."};
                }
                if (c == '(')
                {
                    ++pos_;
                    return Token{Token::Kind::LParen, "("};
                }
                if (c == ')')
                {
                    ++pos_;
                    return Token{Token::Kind::RParen, ")"};
                }
                if (c == '"' || c == '\'')
                    return lex_quoted(c);
                if (c == '&' && peek(1) == '&')
                {
                    pos_ += 2;
                    return Token{Token::Kind::And, "&&"};
                }
                if (c == '|' && peek(1) == '|')
                {
                    pos_ += 2;
                    return Token{Token::Kind::Or, "||"};
                }
                if (c == '=' && peek(1) == '~')
                {
                    pos_ += 2;
                    return Token{Token::Kind::Op, "=~"};
                }
                if (c == '=' && peek(1) == '=')
                {
                    pos_ += 2;
                    return Token{Token::Kind::Op, "=="};
                }
                if (c == '!' && peek(1) == '=')
                {
                    pos_ += 2;
                    return Token{Token::Kind::Op, "!="};
                }
                if (c == '<' && peek(1) == '=')
                {
                    pos_ += 2;
                    return Token{Token::Kind::Op, "<="};
                }
                if (c == '>' && peek(1) == '=')
                {
                    pos_ += 2;
                    return Token{Token::Kind::Op, ">="};
                }
                if (c == '<')
                {
                    ++pos_;
                    return Token{Token::Kind::Op, "<"};
                }
                if (c == '>')
                {
                    ++pos_;
                    return Token{Token::Kind::Op, ">"};
                }

                return lex_word();
            }

            /// @brief Same as next(), but expects the token to be an
            /// identifier (a path segment right after '.') - stricter
            /// character set than a bareword literal (letters/digits/
            /// underscore only, matching schema.py field names), and
            /// distinct from lex_word() so an operator character can
            /// never accidentally be swallowed into a field name.
            std::expected<Token, std::string> next_ident()
            {
                skip_whitespace();
                if (pos_ >= text_.size() || !is_ident_start(text_[pos_]))
                    return std::unexpected("expected a field name after '.'");
                size_t start = pos_;
                while (pos_ < text_.size() && is_ident_char(text_[pos_]))
                    ++pos_;
                return Token{Token::Kind::Ident, std::string(text_.substr(start, pos_ - start))};
            }

        private:
            char peek(size_t ahead) const
            {
                return pos_ + ahead < text_.size() ? text_[pos_ + ahead] : '\0';
            }

            void skip_whitespace()
            {
                while (pos_ < text_.size() && std::isspace(static_cast<unsigned char>(text_[pos_])))
                    ++pos_;
            }

            static bool is_ident_start(char c) { return std::isalpha(static_cast<unsigned char>(c)) || c == '_'; }
            static bool is_ident_char(char c) { return std::isalnum(static_cast<unsigned char>(c)) || c == '_'; }
            static bool is_word_stop(char c)
            {
                return std::isspace(static_cast<unsigned char>(c)) || c == '(' || c == ')' || c == '&' || c == '|';
            }

            std::expected<Token, std::string> lex_quoted(char quote)
            {
                ++pos_; // opening quote
                size_t start = pos_;
                while (pos_ < text_.size() && text_[pos_] != quote)
                    ++pos_;
                if (pos_ >= text_.size())
                    return std::unexpected("unterminated quoted literal");
                std::string value(text_.substr(start, pos_ - start));
                ++pos_; // closing quote
                return Token{Token::Kind::Literal, std::move(value)};
            }

            std::expected<Token, std::string> lex_word()
            {
                size_t start = pos_;
                while (pos_ < text_.size() && !is_word_stop(text_[pos_]))
                    ++pos_;
                if (pos_ == start)
                    return std::unexpected("unexpected character '" + std::string(1, text_[pos_]) + "' in filter expression");
                return Token{Token::Kind::Literal, std::string(text_.substr(start, pos_ - start))};
            }

            std::string_view text_;
            size_t pos_ = 0;
        };

        inline std::expected<FilterOp, std::string> op_from_text(std::string_view text)
        {
            if (text == "==")
                return FilterOp::Eq;
            if (text == "!=")
                return FilterOp::Ne;
            if (text == "<")
                return FilterOp::Lt;
            if (text == "<=")
                return FilterOp::Le;
            if (text == ">")
                return FilterOp::Gt;
            if (text == ">=")
                return FilterOp::Ge;
            if (text == "=~")
                return FilterOp::Glob;
            return std::unexpected("unknown operator '" + std::string(text) + "'");
        }

        class Parser
        {
        public:
            explicit Parser(std::string_view text) : lexer_(text) { advance(); }

            std::expected<FilterExpr, std::string> parse()
            {
                auto expr = parse_or();
                if (!expr)
                    return expr;
                if (current_.kind != Token::Kind::End)
                    return std::unexpected("unexpected trailing text starting at '" + current_.text + "'");
                return expr;
            }

        private:
            void advance()
            {
                auto token = lexer_.next();
                // A lexer error surfaces the next time it's consulted -
                // parse() always checks current_.kind, and an error is
                // reported as an End token paired with had_error_ set, so
                // every call site's normal "unexpected token" handling
                // reports it without duplicating error plumbing everywhere.
                if (!token)
                {
                    had_error_ = true;
                    error_ = token.error();
                    current_ = Token{Token::Kind::End, ""};
                    return;
                }
                current_ = *token;
            }

            std::expected<FilterExpr, std::string> fail_if_lexer_errored()
            {
                if (had_error_)
                    return std::unexpected(error_);
                return FilterExpr{};
            }

            std::expected<FilterExpr, std::string> parse_or()
            {
                auto lhs = parse_and();
                if (!lhs)
                    return lhs;
                if (current_.kind != Token::Kind::Or)
                    return lhs;

                FilterExpr group;
                group.kind = FilterExpr::Kind::Or;
                group.children.push_back(std::move(*lhs));
                while (current_.kind == Token::Kind::Or)
                {
                    advance();
                    auto rhs = parse_and();
                    if (!rhs)
                        return rhs;
                    group.children.push_back(std::move(*rhs));
                }
                return group;
            }

            std::expected<FilterExpr, std::string> parse_and()
            {
                auto lhs = parse_unary();
                if (!lhs)
                    return lhs;
                if (current_.kind != Token::Kind::And)
                    return lhs;

                FilterExpr group;
                group.kind = FilterExpr::Kind::And;
                group.children.push_back(std::move(*lhs));
                while (current_.kind == Token::Kind::And)
                {
                    advance();
                    auto rhs = parse_unary();
                    if (!rhs)
                        return rhs;
                    group.children.push_back(std::move(*rhs));
                }
                return group;
            }

            std::expected<FilterExpr, std::string> parse_unary()
            {
                if (current_.kind == Token::Kind::LParen)
                {
                    advance();
                    auto inner = parse_or();
                    if (!inner)
                        return inner;
                    if (current_.kind != Token::Kind::RParen)
                        return std::unexpected("expected ')'");
                    advance();
                    return inner;
                }
                return parse_comparison();
            }

            std::expected<FilterExpr, std::string> parse_comparison()
            {
                if (current_.kind != Token::Kind::Dot)
                    return std::unexpected("expected a field path starting with '.' at '" + current_.text + "'");

                std::vector<std::string> path;
                while (current_.kind == Token::Kind::Dot)
                {
                    auto ident = lexer_.next_ident();
                    if (!ident)
                        return std::unexpected(ident.error());
                    path.push_back(std::move(ident->text));
                    advance();
                }
                if (path.empty())
                    return std::unexpected("empty field path");

                if (current_.kind != Token::Kind::Op)
                    return std::unexpected("expected a comparison operator after '." + path.back() + "'");
                auto op = op_from_text(current_.text);
                if (!op)
                    return std::unexpected(op.error());
                advance();

                if (current_.kind != Token::Kind::Literal)
                    return std::unexpected("expected a value after operator");
                std::string literal = current_.text;
                advance();

                if (had_error_)
                    return std::unexpected(error_);

                FilterExpr expr;
                expr.kind = FilterExpr::Kind::Comparison;
                expr.path = std::move(path);
                expr.op = *op;
                expr.literal = std::move(literal);
                return expr;
            }

            Lexer lexer_;
            Token current_{Token::Kind::End, ""};
            bool had_error_ = false;
            std::string error_;
        };

        /// @brief Simple `*`/`?` glob match (Tcl `string match` semantics)
        /// - `*` matches any run of characters (including none), `?`
        /// matches exactly one. No escaping - a literal `*`/`?` can't be
        /// matched, matching this project's other glob-lite conventions
        /// (see e.g. layer-name matching elsewhere) rather than a full
        /// pattern language.
        inline bool glob_match(std::string_view pattern, std::string_view text)
        {
            size_t p = 0, t = 0, star_p = std::string_view::npos, star_t = 0;
            while (t < text.size())
            {
                if (p < pattern.size() && (pattern[p] == '?' || pattern[p] == text[t]))
                {
                    ++p;
                    ++t;
                }
                else if (p < pattern.size() && pattern[p] == '*')
                {
                    star_p = p++;
                    star_t = t;
                }
                else if (star_p != std::string_view::npos)
                {
                    p = star_p + 1;
                    t = ++star_t;
                }
                else
                {
                    return false;
                }
            }
            while (p < pattern.size() && pattern[p] == '*')
                ++p;
            return p == pattern.size();
        }

        inline bool compare_string(std::string_view actual, FilterOp op, std::string_view literal)
        {
            switch (op)
            {
            case FilterOp::Eq:
                return actual == literal;
            case FilterOp::Ne:
                return actual != literal;
            case FilterOp::Lt:
                return actual < literal;
            case FilterOp::Le:
                return actual <= literal;
            case FilterOp::Gt:
                return actual > literal;
            case FilterOp::Ge:
                return actual >= literal;
            case FilterOp::Glob:
                return glob_match(literal, actual);
            }
            return false;
        }

        template <typename T>
        bool compare_number(T actual, FilterOp op, std::string_view literal)
        {
            T lit{};
            auto result = std::from_chars(literal.data(), literal.data() + literal.size(), lit);
            // A literal that isn't a number never matches a numeric field
            // (degrade gracefully - e.g. `.width == abc` - rather than an
            // error, matching this project's "expected-missing-data
            // returns empty/false, doesn't throw" convention).
            if (result.ec != std::errc{} || result.ptr != literal.data() + literal.size())
                return false;
            switch (op)
            {
            case FilterOp::Eq:
                return actual == lit;
            case FilterOp::Ne:
                return actual != lit;
            case FilterOp::Lt:
                return actual < lit;
            case FilterOp::Le:
                return actual <= lit;
            case FilterOp::Gt:
                return actual > lit;
            case FilterOp::Ge:
                return actual >= lit;
            case FilterOp::Glob:
                return false; // glob is a string-only operator
            }
            return false;
        }

        inline bool compare_property_value(const PropertyValue &actual, FilterOp op, const std::string &literal)
        {
            switch (actual.type)
            {
            case PropertyValue::Type::STRING:
                return compare_string(actual.string_value, op, literal);
            case PropertyValue::Type::INT:
                return compare_number<int64_t>(actual.int_value, op, literal);
            case PropertyValue::Type::DOUBLE:
                return compare_number<double>(actual.double_value, op, literal);
            }
            return false;
        }

        // Leaf evaluation - shared by both walk() overloads below.
        template <typename DataT>
        bool walk_leaf(const DataT &data, const std::vector<std::string> &path, size_t index, FilterOp op, const std::string &literal)
        {
            auto value = get_field(data, path[index]);
            return value.has_value() && compare_property_value(*value, op, literal);
        }

        // Path resolution once a hop has landed on data with no known id
        // (a non-pooled target - see struct_hpp_j2.py's match_hop() -
        // there's no id concept to propagate further, and none is needed:
        // a non-pooled class's own match_hop() overload never asks for one).
        template <typename RootT, typename DataT>
        bool walk(const RootT &root, const DataT &data, const std::vector<std::string> &path, size_t index, FilterOp op, const std::string &literal)
        {
            if (index + 1 == path.size())
                return walk_leaf(data, path, index, op, literal);
            return match_hop(data, path[index], [&](auto &&...target) -> bool
                              { return walk(root, target..., path, index + 1, op, literal); });
        }

        // Path resolution when the current object is pooled - its own id
        // is required so a *further* hop landing on another pooled class
        // can keep going (match_hop()'s pooled overload always needs one).
        template <typename RootT, typename IdT, typename DataT>
        bool walk(const RootT &root, IdT id, const DataT &data, const std::vector<std::string> &path, size_t index, FilterOp op, const std::string &literal)
        {
            if (index + 1 == path.size())
                return walk_leaf(data, path, index, op, literal);
            return match_hop(root, id, data, path[index], [&](auto &&...target) -> bool
                              { return walk(root, target..., path, index + 1, op, literal); });
        }
    }

    /// @brief Parse a filter-expression string (see this header's own
    /// grammar comment) into a FilterExpr, or an error message describing
    /// why it couldn't be parsed - a malformed TCL `-filter {...}` string
    /// is expected-user-input-shaped, not a programming bug, so this
    /// reports rather than throws (matching this project's "no exceptions
    /// for expected-missing-data paths" convention).
    inline std::expected<FilterExpr, std::string> parse_filter_expression(std::string_view text)
    {
        return filter_detail::Parser(text).parse();
    }

    /// @brief Evaluate a parsed filter expression against one object -
    /// `id`/`data` as `Root::search_x`'s generated `predicate(root, id,
    /// data)` callback already supplies them. Walks `expr.path` through
    /// `match_hop()` for every segment but the last (see struct_hpp_j2.py's
    /// own comment for the two-call-shape contract this relies on),
    /// then compares the leaf field via `get_field()`.
    template <typename RootT, typename IdT, typename DataT>
    bool evaluate_filter(const FilterExpr &expr, const RootT &root, IdT id, const DataT &data)
    {
        switch (expr.kind)
        {
        case FilterExpr::Kind::And:
            for (const auto &child : expr.children)
                if (!evaluate_filter(child, root, id, data))
                    return false;
            return true;
        case FilterExpr::Kind::Or:
            for (const auto &child : expr.children)
                if (evaluate_filter(child, root, id, data))
                    return true;
            return false;
        case FilterExpr::Kind::Comparison:
            if (expr.path.empty())
                return false;
            return filter_detail::walk(root, id, data, expr.path, 0, expr.op, expr.literal);
        }
        return false;
    }
}
