// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Raw Dart FFI bindings for backend/src/api/api.hpp, the LEF Layout Editor
/// C API. Regenerate with `dart run ffigen --config ffigen.yaml` whenever
/// api.hpp changes; never hand-edit this file's output directly.
///
class LefEditorPluginBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LefEditorPluginBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LefEditorPluginBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// @brief Allocate a new, empty editor instance (no LEF loaded, no
  /// Design selected, 0x0 viewport). Never returns null.
  ffi.Pointer<LeHandle> le_create() {
    return _le_create();
  }

  late final _le_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<LeHandle> Function()>>(
        'le_create',
      );
  late final _le_create = _le_createPtr
      .asFunction<ffi.Pointer<LeHandle> Function()>();

  /// @brief Destroy an instance created by le_create(). Safe to call
  /// with a null handle (no-op), matching free()'s convention.
  void le_destroy(ffi.Pointer<LeHandle> handle) {
    return _le_destroy(handle);
  }

  late final _le_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<LeHandle>)>>(
        'le_destroy',
      );
  late final _le_destroy = _le_destroyPtr
      .asFunction<void Function(ffi.Pointer<LeHandle>)>();

  /// @brief Read a LEF file into this handle's shared Root, deriving a
  /// library name from the file's stem. Safe to call multiple times on
  /// the same handle - e.g. a tech file (LAYER definitions, no macros)
  /// followed by one or more macro files that reference those layers by
  /// name, matching LEFReader::read_lef's own existing-Technology reuse
  /// (pass the tech file first when a macro file depends on it - see
  /// render_preview.cpp for the same convention already used there).
  /// Returns 0 on success, matching LEFReader::read_lef's own result
  /// code (nonzero otherwise, including if handle or path is null).
  int le_read_lef(ffi.Pointer<LeHandle> handle, ffi.Pointer<ffi.Char> path) {
    return _le_read_lef(handle, path);
  }

  late final _le_read_lefPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<LeHandle>, ffi.Pointer<ffi.Char>)
        >
      >('le_read_lef');
  late final _le_read_lef = _le_read_lefPtr
      .asFunction<int Function(ffi.Pointer<LeHandle>, ffi.Pointer<ffi.Char>)>();

  /// @brief Number of Designs currently loaded across every LEF file
  /// read into this handle so far. 0 if handle is null.
  int le_design_count(ffi.Pointer<LeHandle> handle) {
    return _le_design_count(handle);
  }

  late final _le_design_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<LeHandle>)>>(
        'le_design_count',
      );
  late final _le_design_count = _le_design_countPtr
      .asFunction<int Function(ffi.Pointer<LeHandle>)>();

  /// @brief Name of the Design at `index` (0..le_design_count()-1).
  /// Returns null if handle is null or index is out of range. The
  /// returned pointer is owned by the handle's Root - valid until the
  /// handle is destroyed (no Design-removal API exists yet), never
  /// owned by the caller.
  ffi.Pointer<ffi.Char> le_design_name(
    ffi.Pointer<LeHandle> handle,
    int index,
  ) {
    return _le_design_name(handle, index);
  }

  late final _le_design_namePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<LeHandle>, ffi.Int32)
        >
      >('le_design_name');
  late final _le_design_name = _le_design_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<LeHandle>, int)>();

  /// @brief Select the Design at `index` as the one le_render_pixel_buffer()
  /// renders (its Abstract view). Returns 0 on success, nonzero if
  /// handle is null or index is out of range - the current selection is
  /// left unchanged on failure.
  int le_set_current_design(ffi.Pointer<LeHandle> handle, int index) {
    return _le_set_current_design(handle, index);
  }

  late final _le_set_current_designPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<LeHandle>, ffi.Int32)>
      >('le_set_current_design');
  late final _le_set_current_design = _le_set_current_designPtr
      .asFunction<int Function(ffi.Pointer<LeHandle>, int)>();

  /// @brief Number of Libraries currently loaded - one per le_read_lef()
  /// call so far (see its own comment: each derives a fresh Library from
  /// its file's stem). 0 if handle is null. The top level of a
  /// Library -> Design -> Abstract browser widget; see
  /// le_library_design_count()/le_library_design_at() for the next level.
  int le_library_count(ffi.Pointer<LeHandle> handle) {
    return _le_library_count(handle);
  }

  late final _le_library_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<LeHandle>)>>(
        'le_library_count',
      );
  late final _le_library_count = _le_library_countPtr
      .asFunction<int Function(ffi.Pointer<LeHandle>)>();

  /// @brief The Library at `index` (0..le_library_count()-1). An
  /// all-invalid/null row (id.index == UINT32_MAX, name == null) if
  /// handle is null or index is out of range, rather than crashing.
  LeLibraryInfo le_library_at(ffi.Pointer<LeHandle> handle, int index) {
    return _le_library_at(handle, index);
  }

  late final _le_library_atPtr =
      _lookup<
        ffi.NativeFunction<
          LeLibraryInfo Function(ffi.Pointer<LeHandle>, ffi.Int32)
        >
      >('le_library_at');
  late final _le_library_at = _le_library_atPtr
      .asFunction<LeLibraryInfo Function(ffi.Pointer<LeHandle>, int)>();

  /// @brief Number of Designs belonging to the Library at
  /// `library_index` (into the same enumeration le_library_at() uses).
  /// 0 if handle is null or library_index is out of range.
  int le_library_design_count(ffi.Pointer<LeHandle> handle, int library_index) {
    return _le_library_design_count(handle, library_index);
  }

  late final _le_library_design_countPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<LeHandle>, ffi.Int32)>
      >('le_library_design_count');
  late final _le_library_design_count = _le_library_design_countPtr
      .asFunction<int Function(ffi.Pointer<LeHandle>, int)>();

  /// @brief The Design at `design_index` within the Library at
  /// `library_index` (0..le_library_design_count(library_index)-1). An
  /// all-invalid/null row if handle is null or either index is out of
  /// range, rather than crashing.
  LeDesignInfo le_library_design_at(
    ffi.Pointer<LeHandle> handle,
    int library_index,
    int design_index,
  ) {
    return _le_library_design_at(handle, library_index, design_index);
  }

  late final _le_library_design_atPtr =
      _lookup<
        ffi.NativeFunction<
          LeDesignInfo Function(ffi.Pointer<LeHandle>, ffi.Int32, ffi.Int32)
        >
      >('le_library_design_at');
  late final _le_library_design_at = _le_library_design_atPtr
      .asFunction<LeDesignInfo Function(ffi.Pointer<LeHandle>, int, int)>();

  /// @brief Select a Design by its stable LeDesignId (e.g. one read from
  /// le_library_design_at()'s LeDesignInfo::id) as the one
  /// le_render_pixel_buffer() renders, same effect as
  /// le_set_current_design() but addressed by identity instead of a
  /// position in the flat le_design_count() list - the natural fit for a
  /// browser widget's row click, which already has the Design's
  /// LeDesignId on hand and shouldn't need to re-derive a flat index for
  /// it. Returns 0 on success, nonzero if handle is null or design_id
  /// doesn't name a Design currently loaded on this handle - the current
  /// selection is left unchanged on failure.
  int le_set_current_design_by_id(
    ffi.Pointer<LeHandle> handle,
    LeDesignId design_id,
  ) {
    return _le_set_current_design_by_id(handle, design_id);
  }

  late final _le_set_current_design_by_idPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<LeHandle>, LeDesignId)>
      >('le_set_current_design_by_id');
  late final _le_set_current_design_by_id = _le_set_current_design_by_idPtr
      .asFunction<int Function(ffi.Pointer<LeHandle>, LeDesignId)>();

  /// @brief Number of layer-widget rows currently available - mirrors
  /// ViewLayerSet::rows() directly (see LeLayerRow's own comment: this
  /// includes BOUNDARY and any future non-Technology-derived "extra"
  /// row, not just physical Layers), so this doesn't care whether a
  /// Technology has even been declared yet - it's simply however many
  /// rows the handle's current ViewLayerSet happens to have (0 if
  /// handle is null or none has been built yet, e.g. before the first
  /// le_read_lef() call). See le_layer_at() for each row's contents.
  int le_layer_count(ffi.Pointer<LeHandle> handle) {
    return _le_layer_count(handle);
  }

  late final _le_layer_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<LeHandle>)>>(
        'le_layer_count',
      );
  late final _le_layer_count = _le_layer_countPtr
      .asFunction<int Function(ffi.Pointer<LeHandle>)>();

  /// @brief The row at `row_index` (0..le_layer_count()-1). An
  /// all-invalid/null row (name == null) if handle is null or row_index
  /// is out of range, rather than crashing.
  LeLayerRow le_layer_at(ffi.Pointer<LeHandle> handle, int row_index) {
    return _le_layer_at(handle, row_index);
  }

  late final _le_layer_atPtr =
      _lookup<
        ffi.NativeFunction<
          LeLayerRow Function(ffi.Pointer<LeHandle>, ffi.Int32)
        >
      >('le_layer_at');
  late final _le_layer_at = _le_layer_atPtr
      .asFunction<LeLayerRow Function(ffi.Pointer<LeHandle>, int)>();

  /// @brief Number of distinct purposes across the handle's current
  /// ViewLayerSet - mirrors ViewLayerSet::purposes() directly. The
  /// "columns" axis of a layer visibility/selectability widget,
  /// independent of any row/layer (see le_purpose_at()). 0 if handle is
  /// null or no ViewLayerSet has been built yet.
  int le_purpose_count(ffi.Pointer<LeHandle> handle) {
    return _le_purpose_count(handle);
  }

  late final _le_purpose_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<LeHandle>)>>(
        'le_purpose_count',
      );
  late final _le_purpose_count = _le_purpose_countPtr
      .asFunction<int Function(ffi.Pointer<LeHandle>)>();

  /// @brief The purpose at `index` (0..le_purpose_count()-1) - mirrors
  /// le::ViewLayerPurpose's declaration order: 0 = TERMINAL,
  /// 1 = OBSTRUCTION, 2 = BOUNDARY. Returns -1 if handle is null or
  /// index is out of range, rather than crashing.
  int le_purpose_at(ffi.Pointer<LeHandle> handle, int index) {
    return _le_purpose_at(handle, index);
  }

  late final _le_purpose_atPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<LeHandle>, ffi.Int32)>
      >('le_purpose_at');
  late final _le_purpose_at = _le_purpose_atPtr
      .asFunction<int Function(ffi.Pointer<LeHandle>, int)>();

  /// @brief Current visibility of every ViewLayer whose LeLayerRow::name
  /// is `layer_name` (case-sensitive exact match) - i.e. a whole row
  /// (every purpose-column of it) together, not one column - a
  /// coarser-grained "layer visibility widget" model than one toggle per
  /// grid cell: see le_is_purpose_visible() for the other axis, and
  /// Scene::is_view_layer_visible for how a specific column's effective
  /// visibility combines both. Visible by default until toggled. Returns
  /// nonzero (visible) if handle or layer_name is null, matching Scene's
  /// own "unknown name defaults to visible" default.
  int le_is_layer_name_visible(
    ffi.Pointer<LeHandle> handle,
    ffi.Pointer<ffi.Char> layer_name,
  ) {
    return _le_is_layer_name_visible(handle, layer_name);
  }

  late final _le_is_layer_name_visiblePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<LeHandle>, ffi.Pointer<ffi.Char>)
        >
      >('le_is_layer_name_visible');
  late final _le_is_layer_name_visible = _le_is_layer_name_visiblePtr
      .asFunction<int Function(ffi.Pointer<LeHandle>, ffi.Pointer<ffi.Char>)>();

  /// @brief Set the visibility of every ViewLayer whose LeLayerRow::name
  /// is `layer_name` - e.g. a layer-visibility widget's row-header
  /// checkbox. Mirrors Scene::set_layer_name_visible directly (affects
  /// rendering - see Pipeline::filter_by_layer_visibility). A no-op if
  /// handle or layer_name is null.
  void le_set_layer_name_visible(
    ffi.Pointer<LeHandle> handle,
    ffi.Pointer<ffi.Char> layer_name,
    int visible,
  ) {
    return _le_set_layer_name_visible(handle, layer_name, visible);
  }

  late final _le_set_layer_name_visiblePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<LeHandle>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
          )
        >
      >('le_set_layer_name_visible');
  late final _le_set_layer_name_visible = _le_set_layer_name_visiblePtr
      .asFunction<
        void Function(ffi.Pointer<LeHandle>, ffi.Pointer<ffi.Char>, int)
      >();

  /// @brief Current visibility of every ViewLayer whose purpose is
  /// `purpose` (mirrors le::ViewLayerPurpose's declaration order: 0 =
  /// TERMINAL, 1 = OBSTRUCTION, 2 = BOUNDARY), across every layer - i.e.
  /// a whole column, not one row. Visible by default until toggled.
  /// Returns nonzero (visible) if handle is null.
  int le_is_purpose_visible(ffi.Pointer<LeHandle> handle, int purpose) {
    return _le_is_purpose_visible(handle, purpose);
  }

  late final _le_is_purpose_visiblePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<LeHandle>, ffi.Int32)>
      >('le_is_purpose_visible');
  late final _le_is_purpose_visible = _le_is_purpose_visiblePtr
      .asFunction<int Function(ffi.Pointer<LeHandle>, int)>();

  /// @brief Set the visibility of every ViewLayer whose purpose is
  /// `purpose`, across every layer - e.g. a layer-visibility widget's
  /// column-header checkbox. Mirrors Scene::set_purpose_visible directly
  /// (affects rendering). A no-op if handle is null.
  void le_set_purpose_visible(
    ffi.Pointer<LeHandle> handle,
    int purpose,
    int visible,
  ) {
    return _le_set_purpose_visible(handle, purpose, visible);
  }

  late final _le_set_purpose_visiblePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<LeHandle>, ffi.Int32, ffi.Int32)
        >
      >('le_set_purpose_visible');
  late final _le_set_purpose_visible = _le_set_purpose_visiblePtr
      .asFunction<void Function(ffi.Pointer<LeHandle>, int, int)>();

  /// @brief Current selectability of every ViewLayer whose LeLayerRow::name
  /// is `layer_name` - see le_is_layer_name_visible()'s comment for the
  /// general row/column model this mirrors. Selectable by default until
  /// toggled. Purely an interaction-layer concern (no hit-testing/
  /// click-to-select API exists yet to consult it) - doesn't affect
  /// rendering. Returns nonzero (selectable) if handle or layer_name is
  /// null.
  int le_is_layer_name_selectable(
    ffi.Pointer<LeHandle> handle,
    ffi.Pointer<ffi.Char> layer_name,
  ) {
    return _le_is_layer_name_selectable(handle, layer_name);
  }

  late final _le_is_layer_name_selectablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<LeHandle>, ffi.Pointer<ffi.Char>)
        >
      >('le_is_layer_name_selectable');
  late final _le_is_layer_name_selectable = _le_is_layer_name_selectablePtr
      .asFunction<int Function(ffi.Pointer<LeHandle>, ffi.Pointer<ffi.Char>)>();

  /// @brief Set the selectability of every ViewLayer whose LeLayerRow::name
  /// is `layer_name`. Mirrors Scene::set_layer_name_selectable directly.
  /// A no-op if handle or layer_name is null.
  void le_set_layer_name_selectable(
    ffi.Pointer<LeHandle> handle,
    ffi.Pointer<ffi.Char> layer_name,
    int selectable,
  ) {
    return _le_set_layer_name_selectable(handle, layer_name, selectable);
  }

  late final _le_set_layer_name_selectablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<LeHandle>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
          )
        >
      >('le_set_layer_name_selectable');
  late final _le_set_layer_name_selectable = _le_set_layer_name_selectablePtr
      .asFunction<
        void Function(ffi.Pointer<LeHandle>, ffi.Pointer<ffi.Char>, int)
      >();

  /// @brief Current selectability of every ViewLayer whose purpose is
  /// `purpose`, across every layer. Selectable by default until toggled.
  /// Returns nonzero (selectable) if handle is null.
  int le_is_purpose_selectable(ffi.Pointer<LeHandle> handle, int purpose) {
    return _le_is_purpose_selectable(handle, purpose);
  }

  late final _le_is_purpose_selectablePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<LeHandle>, ffi.Int32)>
      >('le_is_purpose_selectable');
  late final _le_is_purpose_selectable = _le_is_purpose_selectablePtr
      .asFunction<int Function(ffi.Pointer<LeHandle>, int)>();

  /// @brief Set the selectability of every ViewLayer whose purpose is
  /// `purpose`, across every layer. Mirrors Scene::set_purpose_selectable
  /// directly. A no-op if handle is null.
  void le_set_purpose_selectable(
    ffi.Pointer<LeHandle> handle,
    int purpose,
    int selectable,
  ) {
    return _le_set_purpose_selectable(handle, purpose, selectable);
  }

  late final _le_set_purpose_selectablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<LeHandle>, ffi.Int32, ffi.Int32)
        >
      >('le_set_purpose_selectable');
  late final _le_set_purpose_selectable = _le_set_purpose_selectablePtr
      .asFunction<void Function(ffi.Pointer<LeHandle>, int, int)>();

  /// @brief Zoom the viewport, keeping the dbu point under screen pixel
  /// (x, y) fixed on screen. `factor` is a signed fractional step applied
  /// to the current scale (new_scale = scale * (1 + factor)) - positive
  /// zooms in, negative zooms out (e.g. 0.1 zooms in 10%, -0.1 zooms out
  /// 10%); a factor <= -1.0 (which would make new_scale non-positive) is
  /// ignored, same guard as Scene::set_scale. `x`/`y` are in the same
  /// pixel space as le_render_pixel_buffer()'s output image - top-left
  /// origin, y increasing downward (see api.hpp's LePixelBuffer) - not
  /// Renderer's own pre-Y-flip pixel space, since this is meant to be fed
  /// straight from a pointer/tap event on the rendered image. A no-op if
  /// handle is null. Backend now owns pan/scale entirely - there is no
  /// direct pan/scale setter; use le_fit_scene() to reset to a known view.
  void le_zoom(ffi.Pointer<LeHandle> handle, double factor, int x, int y) {
    return _le_zoom(handle, factor, x, y);
  }

  late final _le_zoomPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<LeHandle>,
            ffi.Double,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('le_zoom');
  late final _le_zoom = _le_zoomPtr
      .asFunction<void Function(ffi.Pointer<LeHandle>, double, int, int)>();

  /// @brief Pan the viewport by a fraction of its own size, in dbu-space
  /// directions (positive x_factor/y_factor move the view toward
  /// increasing dbu x/y - the same "up is positive" convention as the
  /// database itself, not screen space): pan += (x_factor, y_factor) *
  /// viewport_size / scale. E.g. x_factor = 1.0 pans right by exactly one
  /// full viewport width of content. A no-op if handle is null.
  void le_pan(ffi.Pointer<LeHandle> handle, double x_factor, double y_factor) {
    return _le_pan(handle, x_factor, y_factor);
  }

  late final _le_panPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<LeHandle>, ffi.Double, ffi.Double)
        >
      >('le_pan');
  late final _le_pan = _le_panPtr
      .asFunction<void Function(ffi.Pointer<LeHandle>, double, double)>();

  /// @brief Set the viewport size in pixels - also the size of the
  /// buffer le_render_pixel_buffer() produces. Mirrors
  /// Scene::set_viewport_size directly.
  void le_set_viewport_size(
    ffi.Pointer<LeHandle> handle,
    int width_px,
    int height_px,
  ) {
    return _le_set_viewport_size(handle, width_px, height_px);
  }

  late final _le_set_viewport_sizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<LeHandle>, ffi.Int32, ffi.Int32)
        >
      >('le_set_viewport_size');
  late final _le_set_viewport_size = _le_set_viewport_sizePtr
      .asFunction<void Function(ffi.Pointer<LeHandle>, int, int)>();

  /// @brief Fit the viewport's pan/scale to the currently selected
  /// Design's content bbox: uniform scale (no stretch) so the content
  /// fills the viewport set via le_set_viewport_size() with `padding_px`
  /// of margin on every side, pan centering it. Mirrors
  /// Scene::fit_to_content, using Pipeline::generate_shapes' output for
  /// the bbox (same shapes le_render_pixel_buffer() would draw). A no-op
  /// if handle is null; degrades to scale 1.0 / pan (0, 0) if no Design
  /// is selected or its Abstract has no shapes, rather than crashing.
  void le_fit_scene(ffi.Pointer<LeHandle> handle, int padding_px) {
    return _le_fit_scene(handle, padding_px);
  }

  late final _le_fit_scenePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<LeHandle>, ffi.Int32)>
      >('le_fit_scene');
  late final _le_fit_scene = _le_fit_scenePtr
      .asFunction<void Function(ffi.Pointer<LeHandle>, int)>();

  /// @brief Run the full pipeline+render chain (generate -> filter ->
  /// filter -> transform -> picture -> rasterize) for the currently
  /// selected Design and viewport, returning the resulting pixel
  /// buffer. Each stage is cached internally (see Pipeline/Renderer) -
  /// calling this again with nothing changed since the last call is
  /// close to free; only viewport/selection changes actually recompute.
  /// Returns an all-zero/null LePixelBuffer if handle is null. No
  /// Design selected (le_set_current_design was never called) degrades
  /// gracefully to an empty (but correctly-sized, non-null) buffer
  /// rather than crashing - Root/Pipeline's own lookups already degrade
  /// gracefully for an unset AbstractId (see pipeline.hpp).
  LePixelBuffer le_render_pixel_buffer(ffi.Pointer<LeHandle> handle) {
    return _le_render_pixel_buffer(handle);
  }

  late final _le_render_pixel_bufferPtr =
      _lookup<
        ffi.NativeFunction<LePixelBuffer Function(ffi.Pointer<LeHandle>)>
      >('le_render_pixel_buffer');
  late final _le_render_pixel_buffer = _le_render_pixel_bufferPtr
      .asFunction<LePixelBuffer Function(ffi.Pointer<LeHandle>)>();
}

/// 7.18.1.2 Minimum-width integer types
typedef int_least8_t = ffi.Int8;
typedef Dartint_least8_t = int;
typedef int_least16_t = ffi.Int16;
typedef Dartint_least16_t = int;
typedef int_least32_t = ffi.Int32;
typedef Dartint_least32_t = int;
typedef int_least64_t = ffi.Int64;
typedef Dartint_least64_t = int;
typedef uint_least8_t = ffi.Uint8;
typedef Dartuint_least8_t = int;
typedef uint_least16_t = ffi.Uint16;
typedef Dartuint_least16_t = int;
typedef uint_least32_t = ffi.Uint32;
typedef Dartuint_least32_t = int;
typedef uint_least64_t = ffi.Uint64;
typedef Dartuint_least64_t = int;

/// 7.18.1.3 Fastest-width integer types
typedef int_fast8_t = ffi.Int8;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Int16;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Int32;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Int64;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.Uint8;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.Uint16;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.Uint32;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.Uint64;
typedef Dartuint_fast64_t = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.LongLong;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLongLong;
typedef Dart__uint64_t = int;
typedef __darwin_intptr_t = ffi.Long;
typedef Dart__darwin_intptr_t = int;
typedef __darwin_natural_t = ffi.UnsignedInt;
typedef Dart__darwin_natural_t = int;

/// The rune type below is declared to be an ``int'' instead of the more natural
/// ``unsigned long'' or ``long''.  Two things are happening here.  It is not
/// unsigned so that EOF (-1) can be naturally assigned to it and used.  Also,
/// it looks like 10646 will be a 31 bit standard.  This means that if your
/// ints cannot hold 32 bits, you will be in trouble.  The reason an int was
/// chosen over a long is that the is*() and to*() routines take ints (says
/// ANSI C), but they use __darwin_ct_rune_t instead of int.  By changing it
/// here, you lose a bit of ANSI conformance, but your programs will still
/// work.
///
/// NOTE: rune_t is not covered by ANSI nor other standards, and should not
/// be instantiated outside of lib/libc/locale.  Use wchar_t.  wchar_t and
/// rune_t must be the same type.  Also wint_t must be no narrower than
/// wchar_t, and should also be able to hold all members of the largest
/// character set plus one extra value (WEOF). wint_t must be at least 16 bits.
typedef __darwin_ct_rune_t = ffi.Int;
typedef Dart__darwin_ct_rune_t = int;

/// mbstate_t is an opaque object to keep conversion state, during multibyte
/// stream conversions.  The content must not be referenced by user programs.
final class __mbstate_t extends ffi.Union {
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  /// for alignment
  @ffi.LongLong()
  external int _mbstateL;
}

typedef __darwin_mbstate_t = __mbstate_t;
typedef __darwin_ptrdiff_t = ffi.Long;
typedef Dart__darwin_ptrdiff_t = int;
typedef __darwin_size_t = ffi.UnsignedLong;
typedef Dart__darwin_size_t = int;
typedef __builtin_va_list = ffi.Pointer<ffi.Char>;
typedef __darwin_va_list = __builtin_va_list;
typedef __darwin_wchar_t = ffi.Int;
typedef Dart__darwin_wchar_t = int;
typedef __darwin_rune_t = __darwin_wchar_t;
typedef __darwin_wint_t = ffi.Int;
typedef Dart__darwin_wint_t = int;
typedef __darwin_clock_t = ffi.UnsignedLong;
typedef Dart__darwin_clock_t = int;
typedef __darwin_socklen_t = __uint32_t;
typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;
typedef __darwin_time_t = ffi.Long;
typedef Dart__darwin_time_t = int;
typedef __darwin_blkcnt_t = __int64_t;
typedef __darwin_blksize_t = __int32_t;
typedef __darwin_dev_t = __int32_t;
typedef __darwin_fsblkcnt_t = ffi.UnsignedInt;
typedef Dart__darwin_fsblkcnt_t = int;
typedef __darwin_fsfilcnt_t = ffi.UnsignedInt;
typedef Dart__darwin_fsfilcnt_t = int;
typedef __darwin_gid_t = __uint32_t;
typedef __darwin_id_t = __uint32_t;
typedef __darwin_ino64_t = __uint64_t;
typedef __darwin_ino_t = __darwin_ino64_t;
typedef __darwin_mach_port_name_t = __darwin_natural_t;
typedef __darwin_mach_port_t = __darwin_mach_port_name_t;
typedef __darwin_mode_t = __uint16_t;
typedef __darwin_off_t = __int64_t;
typedef __darwin_pid_t = __int32_t;
typedef __darwin_sigset_t = __uint32_t;
typedef __darwin_suseconds_t = __int32_t;
typedef __darwin_uid_t = __uint32_t;
typedef __darwin_useconds_t = __uint32_t;

final class __darwin_pthread_handler_rec extends ffi.Struct {
  /// Routine to call
  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>
  >
  __routine;

  /// Argument to pass
  external ffi.Pointer<ffi.Void> __arg;

  external ffi.Pointer<__darwin_pthread_handler_rec> __next;
}

final class _opaque_pthread_attr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_cond_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_condattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutex_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutexattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_once_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlock_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([192])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlockattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  external ffi.Pointer<__darwin_pthread_handler_rec> __cleanup_stack;

  @ffi.Array.multi([8176])
  external ffi.Array<ffi.Char> __opaque;
}

typedef __darwin_pthread_attr_t = _opaque_pthread_attr_t;
typedef __darwin_pthread_cond_t = _opaque_pthread_cond_t;
typedef __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
typedef __darwin_pthread_key_t = ffi.UnsignedLong;
typedef Dart__darwin_pthread_key_t = int;
typedef __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
typedef __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
typedef __darwin_pthread_once_t = _opaque_pthread_once_t;
typedef __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
typedef __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
typedef __darwin_pthread_t = ffi.Pointer<_opaque_pthread_t>;
typedef intmax_t = ffi.Long;
typedef Dartintmax_t = int;
typedef uintmax_t = ffi.UnsignedLong;
typedef Dartuintmax_t = int;

final class LeHandle extends ffi.Opaque {}

/// @brief Raw RGBA8888 pixel buffer, mirroring render::PixelBuffer but
/// using explicit fixed-width types (not `int`/`size_t`, whose width
/// isn't guaranteed identical across toolchains) for a stable FFI ABI.
/// `data` points into memory owned by the LeHandle's Renderer - valid
/// only until the next le_render_pixel_buffer() call on the same
/// handle (or le_destroy()), never owned by the caller and never to be
/// freed by it. Premultiplied alpha, row-major, top-to-bottom; row_bytes
/// may exceed width * 4 - always index by it, never assume a tight
/// stride (see render.hpp's PixelBuffer for the full format contract).
final class LePixelBuffer extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Int64()
  external int row_bytes;
}

/// @brief Mirrors the database's LibraryId handle (generated/ids.hpp's
/// `Id<LibraryTag>`) for the FFI boundary: a stable identity for one
/// Library, safe to hold onto and pass back into e.g.
/// le_set_current_design_by_id() later without re-deriving it from a
/// position in le_library_at()'s enumeration. `index ==
/// UINT32_MAX` (matching `Id<Tag>::valid()`) marks it invalid - never
/// construct one by hand, only copy one returned by this API.
final class LeLibraryId extends ffi.Struct {
  @ffi.Uint32()
  external int index;

  @ffi.Uint32()
  external int generation;
}

/// @brief Mirrors the database's DesignId handle - see LeLibraryId's
/// comment for the general contract.
final class LeDesignId extends ffi.Struct {
  @ffi.Uint32()
  external int index;

  @ffi.Uint32()
  external int generation;
}

/// @brief Mirrors the database's AbstractId handle - see LeLibraryId's
/// comment for the general contract.
final class LeAbstractId extends ffi.Struct {
  @ffi.Uint32()
  external int index;

  @ffi.Uint32()
  external int generation;
}

/// @brief One row of le_library_at(): a Library's identity and name.
final class LeLibraryInfo extends ffi.Struct {
  external LeLibraryId id;

  /// Owned by the handle's Root - valid until the handle is
  /// destroyed, never owned by the caller. Null if this row is
  /// invalid (out-of-range index or null handle).
  external ffi.Pointer<ffi.Char> name;
}

/// @brief One row of le_library_design_at(): a Design's identity
/// (plus its parent Library's) and name.
final class LeDesignInfo extends ffi.Struct {
  external LeLibraryId library_id;

  external LeDesignId id;

  /// Invalid (index == UINT32_MAX) if this Design has no Abstract
  /// view yet - no DEF/placement-driven Design exists in this
  /// project yet, so every Design read via le_read_lef() has one,
  /// but the field degrades gracefully rather than assume that.
  external LeAbstractId abstract_id;

  /// Owned by the handle's Root - valid until the handle is
  /// destroyed, never owned by the caller. Null if this row is
  /// invalid (out-of-range index or null handle).
  external ffi.Pointer<ffi.Char> name;
}

/// @brief One row of le_layer_at(): a layer-visibility/selectability
/// widget's row-header - a name plus a swatch color, *not* tied to a
/// physical Layer existing - BOUNDARY is a row like any other, and any
/// future non-Technology-derived ("extra") ViewLayer becomes a row the
/// same way. Visibility/selectability are set by this name directly
/// (le_set_layer_name_visible()/le_set_layer_name_selectable()), not
/// by any id here - there's no per-row column list to address (see
/// le_purpose_count()/le_purpose_at() for the other, row-independent
/// "columns" axis).
final class LeLayerRow extends ffi.Struct {
  /// Owned by the handle's Root - valid until the handle is
  /// destroyed, never owned by the caller. Null if this row is
  /// invalid (out-of-range index or null handle).
  external ffi.Pointer<ffi.Char> name;

  /// This row's own outline color, for a swatch next to its name -
  /// not the fill color or FillPattern, which draw_group already
  /// resolves per shape.
  @ffi.Uint8()
  external int color_r;

  @ffi.Uint8()
  external int color_g;

  @ffi.Uint8()
  external int color_b;
}
